export interface Drink {
    idDrink: "";
    strDrink: "";
    strGlass: "";
    strInstructions: "";
    strInstructionsES: "" | null;
    strInstructionsDE: "" | null;
    strInstructionsFR: "" | null;
    strInstructionsIT: "" | null;
    strDrinkThumb: "";
    strIngredient1: "";
    strIngredient2: "" | null;
    strIngredient3: "" | null;
    strIngredient4: "" | null;
    strIngredient5: "" | null;
    strIngredient6: "" | null;
    strIngredient7: "" | null;
    strIngredient8: "" | null;
    strIngredient9: "" | null;
    strIngredient10: "" | null;
    strIngredient11: "" | null;
    strIngredient12: "" | null;
    strIngredient13: "" | null;
    strIngredient14: "" | null;
    strIngredient15: "" | null;
    strMeasure1: "";
    strMeasure2: "" | null;
    strMeasure3: "" | null;
    strMeasure4: "" | null;
    strMeasure5: "" | null;
    strMeasure6: "" | null;
    strMeasure7: "" | null;
    strMeasure8: "" | null;
    strMeasure9: "" | null;
    strMeasure10: "" | null;
    strMeasure11: "" | null;
    strMeasure12: "" | null;
    strMeasure13: "" | null;
    strMeasure14: "" | null;
    strMeasure15: "" | null;
}
